/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEvaluationsIdRouteImport } from './routes/api/evaluations/$id'
import { Route as ApiEvaluationsIdEventsRouteImport } from './routes/api/evaluations/$id/events'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationsIdRoute = ApiEvaluationsIdRouteImport.update({
  id: '/api/evaluations/$id',
  path: '/api/evaluations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationsIdEventsRoute = ApiEvaluationsIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiEvaluationsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRouteWithChildren
  '/api/evaluations/$id/events': typeof ApiEvaluationsIdEventsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRouteWithChildren
  '/api/evaluations/$id/events': typeof ApiEvaluationsIdEventsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/evaluations/$id': typeof ApiEvaluationsIdRouteWithChildren
  '/api/evaluations/$id/events': typeof ApiEvaluationsIdEventsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/evaluations/$id' | '/api/evaluations/$id/events'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/evaluations/$id' | '/api/evaluations/$id/events'
  id: '__root__' | '/' | '/api/evaluations/$id' | '/api/evaluations/$id/events'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEvaluationsIdRoute: typeof ApiEvaluationsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluations/$id': {
      id: '/api/evaluations/$id'
      path: '/api/evaluations/$id'
      fullPath: '/api/evaluations/$id'
      preLoaderRoute: typeof ApiEvaluationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluations/$id/events': {
      id: '/api/evaluations/$id/events'
      path: '/events'
      fullPath: '/api/evaluations/$id/events'
      preLoaderRoute: typeof ApiEvaluationsIdEventsRouteImport
      parentRoute: typeof ApiEvaluationsIdRoute
    }
  }
}

interface ApiEvaluationsIdRouteChildren {
  ApiEvaluationsIdEventsRoute: typeof ApiEvaluationsIdEventsRoute
}

const ApiEvaluationsIdRouteChildren: ApiEvaluationsIdRouteChildren = {
  ApiEvaluationsIdEventsRoute: ApiEvaluationsIdEventsRoute,
}

const ApiEvaluationsIdRouteWithChildren =
  ApiEvaluationsIdRoute._addFileChildren(ApiEvaluationsIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEvaluationsIdRoute: ApiEvaluationsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
